language: node_js

node_js:
    - "node"
    - "6"



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    - make install check



script:
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/43947bb1509aa94c450e

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
